# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Upped NPM Version

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Version Type (major, minor, patch)'     
        required: true
        default: 'patch'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm test

  npm-version:
    needs: build
    if: ${{ contains(['major', 'minor', 'patch'], env.INPUT_VERSION_TYPE) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
        git config user.name "Hao"
        git config user.email "haowebdev@gmail.com"
      - run: npm version ${{env.INPUT_VERSION_TYPE}}
