name: Up NPM Version

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Version Type (major, minor, patch)'     
        required: true
        default: 'patch'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm test

  npm-version:
    needs: build
    if: ${{ github.event.inputs.version_type == 'major' || github.event.inputs.version_type == 'minor' || github.event.inputs.version_type == 'patch'}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git config user.name "Hao"
          git config user.email "haowebdev@gmail.com"
      - run: npm version ${{github.event.inputs.version_type}}
